name: Run Improvibit

on:
  workflow_dispatch: # Manual trigger

jobs:
  improvibit:
    runs-on: ubuntu-latest

    env:
      COMMIT_MESSAGE_FILE: ${{ runner.temp }}/commit_message.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Run AI Agent
        run: |
          MESSAGE=$(tsx ./src/main.ts)
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected. Will commit."
            git add .
            git commit -F "$COMMIT_MESSAGE_FILE"
            git push
          else
            echo "No changes to commit."
          fi
